### PR TITLE
strict types, fixed silence operators, code sorting, connection class, abstract server, abstract client

### PR DESCRIPTION
**Pull request by Byter09**
This time there are no errors or warnings and the analyzer is also happy. So am I.

I hope you did not change too much already to make these changes irrelevant. 🤞 

Next I'd work on the user object or the abstract-iation. Depending on what you're doing right now.

### CODE REVIEW

**Comment by Byter09** [comment]
Please note, that `$temp` in line 57 of Base.php can still be a boolean value if `$data` is empty. Not quite sure about sending empty messages, so I left that in for now.

**Comment by vakata** [comment]
@Byter09 - I just added 2.0.0 which requires PHP 8 and has type hints.

**Comment by Byter09** [comment]
I created this PR nearly 5 years ago. I don't even use PHP anymore and just closed this age old issue hahaha. I appreciate the heads up though haha.

**Comment by vakata** [comment]
hahahah :) I decided to add the note just for other people coming across the PR :)

**Pull request closed without merging**
